# General prompt config
format = """
$directory$git_branch$git_status$python$nodejs$rust$docker_context\
$jobs$cmd_duration$time$line_break$character"""

right_format = "$username@$hostname"

[username]
show_always = true
style_user = "bold green"

[hostname]
ssh_only = false
style = "bold blue"


# Prompt symbol
[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
vimcmd_symbol = "[â®](bold yellow)"
vimcmd_replace_one_symbol = "[â®](bold purple)"
vimcmd_replace_symbol = "[â®](bold purple)"
vimcmd_visual_symbol = "[â®](bold blue)"

# Current directory
[directory]
style = "blue bold"
read_only = " ï ½"
truncation_length = 3
truncation_symbol = "â€¦/"

# Git branch
[git_branch]
symbol = "î‚  "
style = "purple"

[git_status]
conflicted = "conflicted "
ahead = "ahead(${count}) "
behind = "behind(${count}) "
diverged = "diverged "
untracked = "untracked "
modified = "modified "
staged = "staged "
deleted = "deleted "
stashed = "stashed "


# # Git status
# [git_status]
# conflicted = "âš”ï¸ "
# ahead = "â‡¡${count}"
# behind = "â‡£${count}"
# diverged = "â‡•"
# untracked = "ğŸ›¤ï¸ "
# modified = "ğŸ“ "
# staged = "â• "
# deleted = "ğŸ—‘ï¸ "
# stashed = "ğŸ“¦ "
#
# # Python version
# [python]
# symbol = "ğŸ "
# style = "yellow"
# pyenv_version_name = true
#
# # Node.js version
# [nodejs]
# symbol = "îœ˜ "
# style = "green"
#
# # Rust version
# [rust]
# symbol = "ğŸ¦€ "
# style = "red"
#
# # Docker context
# [docker_context]
# symbol = "ğŸ³ "
# style = "cyan"



[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

palette = "catppuccin_mocha"

